version: '3.3'

services:
    node-web-app:
        build: ./frontend
        image: kjax/node-web-app
        command: gatsby develop -H 0.0.0.0
        volumes:
            - ./frontend/src:/home/node/app/src:Z
        ports:
            - "3000:8000"
        restart: always
    db-headless:
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        image: mariadb
        ports:
            - '3307:3306'
        restart: always
    wp-headless:
        build: ./wordpress
        command: bash -c 'ls -la && bash install_wordpress.sh'
        user: root
        depends_on:
            - db-headless
        env_file: ./.env
        volumes:
            - ./wordpress:/var/www/html:z
            - ./docker/plugins:/var/www/plugins 
        ports:
        - '8080:8080'
        restart: always